[package]
name = "cmli"
version = "0.1.0"
edition = "2024"
build = "build/main.rs"

[dependencies]
sym-gen = { git = "https://github.com/lccc-project/sym-gen", features = [
    "std",
] }
cmli-proc-macro.path = "cmli-proc-macro"
paste = "1.0.15"
bitflags = "2.10.0"
bitfield-struct = "0.13.0"
bytemuck = { version = "1.25", features = ["derive", "min_const_generics"] }

[workspace]
members = ["cmli-proc-macro"]

[features]
x86 = []
skyarch = []

default = ["default-archs","default-formats"]
default-archs = ["x86"]
all-archs = ["default-archs", "skyarch"]

elf = []

default-formats = ["elf"]
all-formats = ["default-formats"]
